# Generated by Django 3.1.7 on 2021-04-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='asset_type',
            field=models.CharField(choices=[('Equity', 'Equity'), ('Debt', 'Debt'), ('Liquid ', 'Liquid'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
