# Generated by Django 3.1.7 on 2021-04-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210408_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='AMC',
        ),
    ]
