# Generated by Django 3.1.7 on 2021-04-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210408_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_redeem',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Redemption', 'Redemption'), ('Switch In ', 'Switch In'), ('Switch Out ', 'Switch Out')], max_length=200, null=True),
        ),
    ]
