# Generated by Django 3.1.7 on 2021-04-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product_purchase_redeem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='asset_type',
            field=models.CharField(choices=[('Equity', 'Equity'), ('Debt', 'Debt'), ('Liquid ', 'Liquid'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='folio_No',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='investment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_nav',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_redeem',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Redemption', 'Redemption'), ('Switch In ', 'Switch In'), ('Switch Out ', 'Switch Out')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='units',
            field=models.FloatField(null=True),
        ),
    ]
